name: autorun
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  http: ^0.13.4    
  validators: ^3.0.0
  battery_indicator: ^0.1.0
  geolocator: ^8.2.0
  material_design_icons_flutter: ^5.0.6595
  latlng: ^0.1.0

  
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.3
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  location: ^4.3.0
  form_field_validator: ^1.1.0
  timelines: ^0.1.0
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2  


flutter_icons:
  Android: true
  iOS: true
  image_path: /icons/logoApp.png 

 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  

 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/imgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: MyFlutterApp
       fonts:    
         - asset: assets/icons/MyFlutterApp.ttf
     - family: MyIcons
       fonts:    
         - asset: assets/icons/MyIcons.ttf    
     - family: Password   
       fonts:  
         - asset: assets/icons/Password.ttf
     - family: Eye   
       fonts:  
         - asset: assets/icons/Eye.ttf
     - family: Next   
       fonts:  
         - asset: assets/icons/Next.ttf
     - family: SlideBar   
       fonts:  
         - asset: assets/icons/SlideBar.ttf 
     - family: PanneIcon   
       fonts:  
         - asset: assets/icons/PanneIcon.ttf
     - family: NewIcon   
       fonts:  
         - asset: assets/icons/NewIcon.ttf
     - family: Unlock   
       fonts:  
         - asset: assets/icons/Unlock.ttf
     - family: Batterie   
       fonts:  
         - asset: assets/icons/Batterie.ttf
     - family: Fleche  
       fonts:  
         - asset: assets/icons/Fleche.ttf
     - family: MenuIcon  
       fonts:  
         - asset: assets/icons/MenuIcon.ttf                                      
     #- family: Menu   
     #  fonts:  
      #   - asset: assets/icons/Menu.ttf   
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Nunito
       fonts:
       - asset: assets/fonts/Nunito-light.ttf
         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
